# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest

  # Enable caching if plugin installed
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.33.40"

  host = RbConfig::CONFIG['host_os']

  # Use nfs when running on a unix system
  if host =~ /darwin/
	  config.vm.synced_folder ".", "/vagrant", nfs: true, mount_options: ['rw', 'vers=3', 'tcp', 'fsc']
  elsif host =~ /linux/
	  config.vm.synced_folder ".", "/vagrant", nfs: true, mount_options: ['rw', 'vers=3', 'tcp', 'fsc']
  else
	  config.vm.synced_folder ".", "/vagrant", mount_options: ['dmode=777','fmode=666']
  end

  # Auto assign cpu and ram during provisioning
  config.vm.provider :virtualbox do |v|
      if host =~ /darwin/
        cpus = `sysctl -n hw.ncpu`.to_i
        ram = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
      elsif host =~ /linux/
        cpus = `nproc`.to_i
        ram = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
      else
        cpus = 2
        ram = 4096
      end

      v.customize ["modifyvm", :id, "--memory", ram]
      v.customize ["modifyvm", :id, "--cpus", cpus]
      v.gui = true
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks","site-cookbooks"]
    chef.add_recipe "mycookbook"
  end
end
